##################################################
# file: ProcessingService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      C:\Python26\Scripts\wsdl2py -b http://poligon.machinelearning.ru/processingservice.asmx?WSDL
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from ProcessingService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
GetTaskSoapIn = GED("http://poligon.machinelearning.ru/", "GetTask").pyclass

GetTaskSoapOut = GED("http://poligon.machinelearning.ru/", "GetTaskResponse").pyclass

GetProblemSoapIn = GED("http://poligon.machinelearning.ru/", "GetProblem").pyclass

GetProblemSoapOut = GED("http://poligon.machinelearning.ru/", "GetProblemResponse").pyclass

RegisterResultSoapIn = GED("http://poligon.machinelearning.ru/", "RegisterResult").pyclass

RegisterResultSoapOut = GED("http://poligon.machinelearning.ru/", "RegisterResultResponse").pyclass


# Service Skeletons
class ProcessingService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/processingservice.asmx', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_GetTask(self, ps, **kw):
        request = ps.Parse(GetTaskSoapIn.typecode)
        return request,GetTaskSoapOut()

    soapAction['http://poligon.machinelearning.ru/GetTask'] = 'soap_GetTask'
    root[(GetTaskSoapIn.typecode.nspname,GetTaskSoapIn.typecode.pname)] = 'soap_GetTask'

    def soap_GetProblem(self, ps, **kw):
        request = ps.Parse(GetProblemSoapIn.typecode)
        return request,GetProblemSoapOut()

    soapAction['http://poligon.machinelearning.ru/GetProblem'] = 'soap_GetProblem'
    root[(GetProblemSoapIn.typecode.nspname,GetProblemSoapIn.typecode.pname)] = 'soap_GetProblem'

    def soap_RegisterResult(self, ps, **kw):
        request = ps.Parse(RegisterResultSoapIn.typecode)
        return request,RegisterResultSoapOut()

    soapAction['http://poligon.machinelearning.ru/RegisterResult'] = 'soap_RegisterResult'
    root[(RegisterResultSoapIn.typecode.nspname,RegisterResultSoapIn.typecode.pname)] = 'soap_RegisterResult'

